make safe

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,14 +1,15 @@
 #!/bin/bash
 #
 # Script: install
-# Version: 4.0.6
-# Date: 2016.07.28
+# Description: install script for g2w
+# Version: 4.0.7
+# Date: 2016.08.01
 #
 
 bin_folder=/usr/local/bin
 login_shell_folder=/etc/profile.d
 
-set_alias() {
+set_alias_linux() {
 	local login_script=g2w.sh
 
 	if [ -f $login_script ];then
@@ -24,6 +25,37 @@ set_alias() {
 		echo "can't find $login_script"
 	fi
 }
+
+set_alias_cygwin() {
+	local login_script=g2w.sh
+
+	if [ -f $login_script ];then
+		echo -n "copy $login_script to $login_shell_folder ... "
+		cp $login_script $login_shell_folder
+
+		if [ $? -eq 0 ];then
+			echo ok
+		else
+			echo error
+		fi
+	else
+		echo "can't find $login_script"
+	fi
+}
+
+set_alias() {
+	local os=`uname -o`
+
+	case $os in
+		"Cygwin") set_alias_cygwin
+		;;
+		"GUN/Linux") set_alias_linux
+		;;
+		*) echo "Sorry, we don't support your system now."
+		   exit 0
+		;;
+	esac
+}	
 
 show_messages() {
 	cat <<here
